
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;
using BIS.Api.Authorization;
using BIS.Common.Entities;
using BIS.Common.Helpers;

namespace InSync.Api.Authorization
{
    public class JwtManager: IJwtManager
    {
        private readonly JwtConfig _jwtSettings;

        //private readonly AppSettings _appSettings;

       public JwtManager(IOptions<JwtConfig> jwtSettings )
        {
            _jwtSettings = jwtSettings.Value;
        }
        public string GenerateJwtToken(UserDetail user)
        {

            // Now its ime to define the jwt token which will be responsible of creating our tokens
            var jwtTokenHandler = new JwtSecurityTokenHandler();

            // We get our secret from the appsettings
            var key = Encoding.ASCII.GetBytes(_jwtSettings.Key);

            // we define our token descriptor
            // We need to utilise claims which are properties in our token which gives information about the token
            // which belong to the specific user who it belongs to
            // so it could contain their id, name, email the good part is that these information
            // are generated by our server and identity framework which is valid and trusted
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(new[]
                {
                new Claim(BISConstant.UserId, user.Id.ToString()),
                new Claim(BISConstant.UserName, user.Name.ToString()),
                new Claim(BISConstant.RoleId, user.RoleId.ToString()),
                new Claim(BISConstant.CorpsId, user.CorpsId.ToString()),
                 new Claim(BISConstant.DivisionId, user.DivisionId.ToString()),
                 new Claim(BISConstant.RoleType,user.RoleType.ToString()),
                // the JTI is used for our refresh token which we will be convering in the next video
                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString())
            }),
                Issuer=_jwtSettings.Issuer,
                Audience=_jwtSettings.Audience,
                // the life span of the token needs to be shorter and utilise refresh token to keep the user signedin
                // but since this is a demo app we can extend it to fit our current need
                Expires = DateTime.UtcNow.AddMinutes(_jwtSettings.DurationInMinutes),
                // here we are adding the encryption alogorithim information which will be used to decrypt our token
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha512Signature)
            };
            return jwtTokenHandler.WriteToken(jwtTokenHandler.CreateToken(tokenDescriptor));
        }

         
    }
}















         
