import { BaseEntity } from "./base.model"

export class masterData extends BaseEntity {
  inputLevel: string
  sector: string
  frmn: string
  source: string
  sourceLoc: string
  typeOfLoc: string
  enLocName: string
  aspect: string
  indicator: string
  typeSvlEqpt: string
  noSvlEqpt: string
  masterInputlevelID: number
  masterSectorID: number
  poaseReamrks: string
  irRemarks: string
  iolRemarks: string
  jammingRemarks: string
  htM: string
  tgt: string
  visSrOffrs: string
  ptls: string
  newTps: string
  cvys: string
  obsn: string
  type: string
  timeFrom: string
  timeTo: string
  jammingEqpt: string
  jammingTimefrom: string
  jammingTimeto: string
  jammingDtOfJx: string
  jammingEffect: string
  jammingSpecificationFreq: string
  jammingSpecificationWavelength: string
  jammingSpecificationType: string
  etiNoOfTourists: string
  etiTimefrom: string
  etiTimeto: string
  etiFrequencyDaily: string
  etiFrequencyWeekly: string
  etiFrequencySeasonal: string
  foSTimefrom: string
  foSTimeto: string
  foSSkirmishPurpose: string
  foSSkirmishPlaFmn: string
  foSSkirmishPlaNoOfPers: string
  foSSkirmishPlaNoOfOffrs: string
  foSSkirmishPlaNoOfJcos: string
  foSSkirmishPlaNoOfOr: string
  foSSkirmishPlaNoOfCiv: string
  foSSkirmishPlaNameOfOffrs: string
  foSCas: string
  foSDamageEqpt: string
  foSDamageProperty: string
  foSLossWpn: string
  foSLossAmn: string
  foSLossEqpt: string
  foSCasFatal: string
  foSCasNonFatal: string
  adzTimefrom: string
  adzTimeto: string
  adzNoOfPers: string
  adzActivity: string
  soCUnitType: string
  soCNoOfUnits: string
  soCOccupiedBy: string
  soCNoOfPlaPers: string
  soCNoOfCivs: string
  soCNoOfRbaPers: string
  soCNoOfPapfPers: string
  soCNoOfMilitia: string
  soCNoOfEqpt: string
  soCDescription: string
  gaNoOfGraziers: string
  gaNoOfAnimals: string
  gaNoOfDu: string
  gaGrazierDescription: string
  arAggressiveRecceNoOfPers: string
  arTypeOfPers: string
  arAggressiveRecceDescription: string
  daiNoOfDrones: string
  daiAltM: string
  daiTypeOfDrone: string
  daiFltPathLocA: string
  daiFltPathLocB: string
  daiFltPathLocC: string
  daiFltPathLocD: string
  daiDirnFrom: string
  daiDirnTo: string
  daiIncursionKms: string
  capNoOfAeProximity: string
  capTypeOfAeProximity: string
  capFltPathLocA: string
  capFltPathLocB: string
  capFltPathLocC: string
  capProximityDirnFrom: string
  capProximityDirnTo: string
  capIncursionKms: string
  capActivity: string
  flacNoOfAc: string
  flacAltM: string
  flacTypeOfAc: string
  flacFltPathLocA: string
  flacFltPathLocB: string
  flacFltPathLocC: string
  flacFltPathLocD: string
  flacAcDirnFrom: string
  flacAcDirnTo: string
  flacActivity: string
  avNoOfAePlatform: string
  avAltM: string
  avAirspaceViolationTypeOfAc: string
  avFltPathLocA: string
  avFltPathLocB: string
  avFltPathLocC: string
  avFltPathLocD: string
  avAirspaceViolationDirnFrom: string
  avAirspaceViolationDirnTo: string
  avActivity: string
  avIncursionKms: string
  esfpTypeOfPers: string
  esfpStr: string
  esfpIden: string
  esfpDisposition: string
  esfpDispositionRemarks: string
  rbuTypeOfPers: string
  rbuResBuildUpStr: string
  rbuResBuildUpRemarks: string
  cavConcOfVehsTypeOfVeh: string
  cavConcOfVehsStr: string
  cavConcOfVehsIden: string
  cavConcOfVehsDisposition: string
  cavConcOfVehsDispositionRemarks: string
  teTypeOfTrg: string
  teTrgExStr: string
  teTrgExIden: string
  teTrgExDisposition: string
  teTrgExDispositionRemarks: string
  avnTypeOfVeh: string
  avnStr: string
  avnIden: string
  avnDirnLocA: string
  avnDirnLocB: string
  avnDirnLocC: string
  avnVehsNovMode: string
  avnNomenclatureOfRd: string
  aglmTypeOfArty: string
  aglmTypeOfPlatform: string
  aglmStr: string
  aglmIden: string
  aglmDirnLocA: string
  aglmDirnLocB: string
  aglmDirnLocC: string
  aglmArtyGunsMode: string
  aglmNomenclatureOfRd: string
  aadTypeOfAmn: string
  aadArtyAmnDumpingNoAmnVehs: string
  aadRouteLocA: string
  aadRouteLocB: string
  aadRouteLocC: string
  aadArtyAmnDumpingMode: string
  aadNomenclatureOfRd: string
  ecmTypeOfEqpt: string
  ecmEngrColnNovStr: string
  ecmIden: string
  ecmEngrColnNovRouteLocA: string
  ecmEngrColnNovRouteLocB: string
  ecmEngrColnNovRouteLocC: string
  ecmEngrColnNovMode: string
  ecmNomenclatureOfRd: string
  cowBilleting: string
  cowStorage: string
  cowSplConstr: string
  bidBdrInfraDevpBilleting: string
  bidBdrInfraDevpStorage: string
  bidBdrInfraDevpSplConstr: string
  bidBdrInfraDevpComnInfra: string
  bidBdrInfraDevpRdsCl: string
  bidBdrInfraDevpRdsLength: string
  bidTypeRd: string
  bidBrSpan: string
  bidBrCl: string
  bidNosOfSettlements: string
  bidNoOfHouses: string
  diLocs: string
  diPdsOhp: string
  diPdsWoOhp: string
  diWpnPitsOhp: string
  diWpnPitsWoOhp: string
  diComnTrenchesCovered: string
  diComnTrenchesUncovered: string
  diConstrBy: string
  gaSsSamSiteLocs: string
  gaSsNoOfRamps: string
  adcmAmnDumpsType: string
  adcmAmnDumpsQty: string
  abAddlBilletingType: string
  abAddlBilletingQty: string
  cidTypeOfInfra: string
  cidTypeOfInfraDescription: string
  cidBdrInfraDevpQty: string
  cidFromLoc: string
  cidToLoc: string
  ctrcTypeOfComnInfra: string
  ctrcComnTowerQty: string
  ctrcComnTowerRemarks: string
  ldNoOfShelters: string
  ldModeOfDumping: string
  ldLgsDumpingTypeOfLgs: string
  ldNoOfVehFol: string
  ldNoOfVehSupplies: string
  ldNoOfVehAmn: string
  ldNoOfVehConstrMtrl: string
  ldNoOfTrainsFol: string
  ldNoOfTrainsSupplies: string
  ldNoOfTrainsAmn: string
  ldNoOfTrainsConstrMtrl: string
  bsdBrStoresDumpingNoOfVehs: string
  bsdBrStoresDumpingDescriptionStores: string
  esdEngrStoresDumpingNoOfVehs: string
  esdEngrStoresDumpingDescriptionStores: string
  ivsaIncrVehsInStgAsTypeOfVeh: string
  ivsaIncrVehsInStgAsStr: string
  ivsaIden: string
  ivsaIncrVehsInStgAsDispositionRemarks: string
  ilcIncrLgsCvysStr: string
  ilcIden: string
  ilcIncrLgsCvysRouteLocA: string
  ilcIncrLgsCvysRouteLocB: string
  ilcIncrLgsCvysRouteLocC: string
  ilcIncrLgsCvysMode: string
  ilcNomenclatureOfRd: string
  iltIncrLgsTrainsDateFrom: string
  iltIncrLgsTrainsDateTo: string
  iltNoOfTrainsRoutine: string
  iltNoOfTrainsEnhanced: string
  iltNoOfTrainsIncr: string
  iltRouteOrigin: string
  iltRouteDestination: string
  iltTypeOfLgs: string
  irtIncrRadioTfcDateFrom: string
  irtIncrRadioTfcDateTo: string
  irtTxnBand: string
  irtTypeOfTxn: string
  irtNoOfTxns: string
  teTypeOfForces: string
  teMobTrgExStr: string
  teMobTrgExIden: string
  teMobTrgExDisposition: string
  teMobTrgExEqptOnWheels: string
  teMobTrgExActivityTrg: string
  teActivityRoutine: string
  teHault: string
  rlfPermtLocName: string
  rlfNewLocName: string
  rlfReLocOfForcesDate: string
  rlfQuantumTps: string
  rlfQuantumAVehs: string
  rlfQuantumBVehs: string
  rlfQuantumCVehs: string
  rlfBilletingType: string
  rlfReLocOfForcesIden: string
  tmMobTrsoMovStr: string
  tmEnFmn: string
  tmEnUnit: string
  tmTrsoMovRouteLocA: string
  tmTrsoMovRouteLocB: string
  tmTrsoMovRouteLocC: string
  tmTrsoMovMode: string
  tmHaltLocA: string
  tmHaltLocB: string
  tmHaltLocC: string
  userId: number
  //latest addition 210624
  cidtoiRoadCl: string
  cidtoiRailBroadGauge: string
  cidtoiRailMetreGauge: string
  cidtoiRailRailwaySidings: string
  cidtoiRailDescription: string
  cidtoiAirLengthAitstrip: string
  cidtoiAirNoOfHangers: string
  cidtoiAirNoOfHAS: string
  cidtoiAirMiscShelters: string
  cidtoiBrSpan: string
  cidtoiBrWidth: string
  cidtoiBrCl: string
  cidtoiBrPermt: string
  cidtoiBrTemp: string

  //new addition

  vLoc: string
  vLevel: string
  vFromTime: string
  vTotime: string
  vNoOfIndis: string
  bmmLoc: string
  bmmLevel: string
  bmmFromTime: string
  bmmToTime: string
  bmmNoOfIndis: string
  cLoc: string
  cLevel: string
  cFromTime: string
  cToTime: string
  cNoOfIndis: string
  aDate: string
  aWith: string
  aAgenda: string
  cDate: string
  cWith: string
  jvDate: string
  jvWith: string
  eadLoc: string
  eadDate: string
  eadTime: string
  eadOfCountry: string
  cdmLoc: string
  cdmDate: string
  cdmTime: string
  cdmOfCountry: string
  rdLoc: string
  rdDate: string
  rdTime: string
  rdFromCountry: string
  dapmLoc: string
  dapmDate: string
  dapmTime: string
  dapmTypeOfAgreement: string
  caLoc: string
  caNoOfLocs: string
  caDate: string
  caTime: string
  mdLoc: string
  mdDate: string
  mdTime: string
  mdTgtAgenda: string
  dmpLoc: string
  dmpDate: string
  dmpTime: string
  dmpType: string
  dmpLevel: string
  mrLoc: string
  mrDate: string
  mrTime: string
  mrType: string
  eidLoc: string
  eidDate: string
  eidTime: string
  eidType: string
  teLoc: string
  teDate: string
  teTime: string
  teOnWhom: string
  teType: string
  sLoc: string
  sDate: string
  sTime: string
  sByWhom: string
  sOnWhom: string
  sType: string
  esdLoc: string
  esdDate: string
  esdTime: string
  esdOnWhom: string
  tLoc: string
  tDate: string
  tTime: string
  tBywhom: string
  tToWhom: string
  tType: string
  octrLoc: string
  octrLocTo: string
  octrDate: string
  octrTime: string
  octrTimeTo: string
  puLoc: string
  puDate: string
  puTime: string
  puLevel: string
  ruiLoc: string
  ruiDate: string
  ruiTime: string
  ruiLevel: string
  fiSector: string
  fiDate: string
  fiTime: string
  hcLoc: string
  hcDate: string
  hcTime: string
  hcType: string
  hclLevel: string
  hcoLoc: string
  hcoDate: string
  hcoTime: string
  hcoTimeTo: string
  hcoTgt: string
  hcoLevel: string
  tcinLoc: string
  tcinDate: string
  tcinTime: string
  tcinTimeTo: string
  tcinTgt: string
  htsiLoc: string
  htsiNoOfIndis: string
  htsiPurpose: string
  idsLoc: string
  idsDate: string
  idsSection: string
  ipLoc: string
  ipDate: string
  ipType: string
  ipTypeEqpt_Nos: string
  ipTypeArms_Type: string
  ipTypeArms_Nos: string
  ipTypeAmn_Type: string
  ipTypeAmn_Nos: string
  ipTypeTech_Type: string
  ipTypeTech_Nos: string
  ipTypeWLS_Type: string
  ipTypeWLS_Nos: string
  etrLoc: string
  etrDate: string
  etrNosRect: string
  erLoc: string
  erDate: string
  erRect: string
  fcLoc: string
  fcDate: string
  fcNosRect: string
  ipcLoc: string
  ipcDate: string
  ipcTimeFrom: string
  ipcTimeTo: string
  ipcType: string
  ipcTypeCommercial_Nos: string
  ipcTypeWarship_Type: string
  ipcTypeWarship_Nos: string
  ipcTypeSvl_Type: string
  ipcTypeSvl_Nos: string
  maDate: string
  maWith: string
  maAgenda: string
  ieaLoc: string
  ieaDate: string
  ieaTime: string
  ieaTimeTo: string
  ieaTypeOfActivity: string

  bpmLoc: string
  bpmDate: string
  bpmBetween: string
  bpmTimeFrom: string
  bpmTimeTo: string
  bpmNpm: string
  bpmNpo: string
  biLoc: string
  biDate: string
  biBetween: string
  biTimeFrom: string
  biTimeTo: string
  biNpm: string
  biNpo: string
  cfvLoc: string
  cfvate: string
  cfvBetween: string
  cfvTimeFrom: string
  cfvTimeTo: string
};
export interface searchMast {
  Name: string;
  Sector: string;
  ReportedDate: any;
}
