// <auto-generated />
using System;
using BIS.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIS.API.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BIS.Common.Entities.MasterData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AADArtyAmnDumpingMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AADArtyAmnDumpingNoAmnVehs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AADNomenclatureOfRd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AADRouteLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AADRouteLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AADRouteLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AADTypeOfAmn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAgenda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ABAddlBilletingQty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ABAddlBilletingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADCMAmnDumpsQty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADCMAmnDumpsType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADZActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADZNoOfPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADZTimefrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADZTimeto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLMArtyGunsMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLMDirnLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLMDirnLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLMDirnLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLMIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLMNomenclatureOfRd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLMStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLMTypeOfArty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLMTypeOfPlatform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARAggressiveRecceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARAggressiveRecceNoOfPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARTypeOfPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVAirspaceViolationDirnFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVAirspaceViolationDirnTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVAirspaceViolationTypeOfAc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVAltM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVFltPathLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVFltPathLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVFltPathLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVFltPathLocD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVIncursionKms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVNDirnLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVNDirnLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVNDirnLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVNIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVNNomenclatureOfRd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVNStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVNTypeOfVeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVNVehsNovMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVNoOfAePlatform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AWith")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aspect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIBetween")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDBdrInfraDevpBilleting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDBdrInfraDevpComnInfra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDBdrInfraDevpRdsCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDBdrInfraDevpRdsLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDBdrInfraDevpSplConstr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDBdrInfraDevpStorage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDBrCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDBrSpan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDNoOfHouses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDNosOfSettlements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDTypeRd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BILoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BINpm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BINpo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BITimeFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BITimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BMMFromTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BMMLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BMMLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BMMNoOfIndis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BMMToTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BPMBetween")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BPMDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BPMLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BPMNpm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BPMNpo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BPMTimeFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BPMTimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSDBrStoresDumpingDescriptionStores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSDBrStoresDumpingNoOfVehs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CADate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CALoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CANoOfLocs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAPActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAPFltPathLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAPFltPathLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAPFltPathLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAPIncursionKms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAPNoOfAeProximity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAPProximityDirnFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAPProximityDirnTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAPTypeOfAeProximity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAVConcOfVehsDisposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAVConcOfVehsDispositionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAVConcOfVehsIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAVConcOfVehsStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAVConcOfVehsTypeOfVeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDMDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDMLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDMOfCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDMTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CFromTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDBdrInfraDevpQty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDFromLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIAirLengthAitstrip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIAirMiscShelters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIAirNoOfHAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIAirNoOfHangers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIBrCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIBrPermt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIBrSpan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIBrTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIBrWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIRailBroadGauge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIRailDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIRailMetreGauge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIRailRailwaySidings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTOIRoadCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDToLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTypeOfInfra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIDTypeOfInfraDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNoOfIndis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COWBilleting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COWSplConstr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COWStorage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTRCComnTowerQty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTRCComnTowerRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTRCTypeOfComnInfra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CToTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CWith")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfvBetween")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfvLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfvTimeFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfvTimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cfvate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cvys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAIAltM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAIDirnFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAIDirnTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAIFltPathLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAIFltPathLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAIFltPathLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAIFltPathLocD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAIIncursionKms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAINoOfDrones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAITypeOfDrone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAPMDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAPMLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAPMTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAPMTypeOfAgreement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIComnTrenchesCovered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIComnTrenchesUncovered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIConstrBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DILocs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIPdsOhp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIPdsWoOhp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIWpnPitsOhp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIWpnPitsWoOhp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMPDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMPLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMPLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMPTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMPType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADOfCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EADTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECMEngrColnNovMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECMEngrColnNovRouteLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECMEngrColnNovRouteLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECMEngrColnNovRouteLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECMEngrColnNovStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECMIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECMNomenclatureOfRd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECMTypeOfEqpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EIDDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EIDLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EIDTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EIDType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERRect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDEngrStoresDumpingDescriptionStores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDEngrStoresDumpingNoOfVehs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDOnWhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESFPDisposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESFPDispositionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESFPIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESFPStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESFPTypeOfPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETIFrequencyDaily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETIFrequencySeasonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETIFrequencyWeekly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETINoOfTourists")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETITimefrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETITimeto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETRDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETRLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETRNosRect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnLocName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCNosRect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FISector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FITime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACAcDirnFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACAcDirnTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACAltM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACFltPathLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACFltPathLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACFltPathLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACFltPathLocD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACNoOfAc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLACTypeOfAc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fmn")
                        .HasColumnType("int");

                    b.Property<string>("FoSCas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSCasFatal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSCasNonFatal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSDamageEqpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSDamageProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSLossAmn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSLossEqpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSLossWpn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSSkirmishPlaFmn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSSkirmishPlaNameOfOffrs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSSkirmishPlaNoOfCiv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSSkirmishPlaNoOfJcos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSSkirmishPlaNoOfOffrs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSSkirmishPlaNoOfOr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSSkirmishPlaNoOfPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSSkirmishPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSTimefrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoSTimeto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frmn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GAGrazierDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GANoOfAnimals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GANoOfDu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GANoOfGraziers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GASsNoOfRamps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GASsSamSiteLocs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCLLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCODate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCOLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCOLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCOTgt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCOTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCOTimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTSILoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTSINoOfIndis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTSIPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDSDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDSLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDSSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IEADate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IEALoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IEATime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IEATimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IEATypeOfActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILCIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILCIncrLgsCvysMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILCIncrLgsCvysRouteLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILCIncrLgsCvysRouteLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILCIncrLgsCvysRouteLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILCIncrLgsCvysStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILCNomenclatureOfRd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILTIncrLgsTrainsDateFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILTIncrLgsTrainsDateTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILTNoOfTrainsEnhanced")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILTNoOfTrainsIncr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILTNoOfTrainsRoutine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILTRouteDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILTRouteOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILTTypeOfLgs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IOLRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCTimeFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCTimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCTypeCommercial_Nos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCTypeSvl_Nos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCTypeSvl_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCTypeWarship_Nos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCTypeWarship_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTypeAmn_Nos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTypeAmn_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTypeArms_Nos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTypeArms_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTypeEqpt_Nos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTypeTech_Nos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTypeTech_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTypeWLS_Nos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTypeWLS_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRTIncrRadioTfcDateFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRTIncrRadioTfcDateTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRTNoOfTxns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRTTxnBand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRTTypeOfTxn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IVSAIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IVSAIncrVehsInStgAsDispositionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IVSAIncrVehsInStgAsStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IVSAIncrVehsInStgAsTypeOfVeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JVDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JVWith")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JammingDtOfJx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JammingEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JammingEqpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JammingRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JammingSpecificationFreq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JammingSpecificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JammingSpecificationWavelength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JammingTimefrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JammingTimeto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDLgsDumpingTypeOfLgs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDModeOfDumping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDNoOfShelters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDNoOfTrainsAmn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDNoOfTrainsConstrMtrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDNoOfTrainsFol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDNoOfTrainsSupplies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDNoOfVehAmn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDNoOfVehConstrMtrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDNoOfVehFol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDNoOfVehSupplies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAAgenda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAWith")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDTgtAgenda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MRDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MRLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MRTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MRType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Input Level");

                    b.Property<string>("NewTps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSvlEqpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OCTRDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OCTRLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OCTRLocTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OCTRTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OCTRTimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obsn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POASEReamrks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PUDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PULevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PULoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PUTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ptls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RBUResBuildUpRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RBUResBuildUpStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RBUTypeOfPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RDDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RDFromCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RDLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RDTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLFBilletingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLFNewLocName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLFPermtLocName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLFQuantumAVehs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLFQuantumBVehs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLFQuantumCVehs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLFQuantumTps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLFReLocOfForcesDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLFReLocOfForcesIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUIDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUILevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUILoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUITime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SByWhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOnWhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCNoOfCivs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCNoOfEqpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCNoOfMilitia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCNoOfPapfPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCNoOfPlaPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCNoOfRbaPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCNoOfUnits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCOccupiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCUnitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceLoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TBywhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCINDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCINLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCINTgt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCINTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCINTimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEActivityRoutine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEHault")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEMobTrgExActivityTrg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEMobTrgExDisposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEMobTrgExEqptOnWheels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEMobTrgExIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEMobTrgExStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEOnWhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TETime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TETrgExDisposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TETrgExDispositionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TETrgExIden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TETrgExStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TETypeOfForces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TETypeOfTrg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMEnFmn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMEnUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMHaltLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMHaltLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMHaltLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMMobTrsoMovStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMTrsoMovMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMTrsoMovRouteLocA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMTrsoMovRouteLocB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMTrsoMovRouteLocC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TToWhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tgt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfLoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeSvlEqpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VFromTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VNoOfIndis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VTotime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisSrOffrs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MasterData");
                });
#pragma warning restore 612, 618
        }
    }
}
